apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-exporter-sentinel-v7
  namespace: redis
spec:
  serviceName: redis-exporter-sentinel-v7
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter-sentinel-v7
  template:
    metadata:
      annotations:
        telegraf.influxdata.com/interval: 1s
        telegraf.influxdata.com/inputs: |+
          [[inputs.cpu]]
            percpu = false
            totalcpu = true
            collect_cpu_time = true
            report_active = true

          [[inputs.disk]]
            ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

          [[inputs.diskio]]

          [[inputs.kernel]]

          [[inputs.mem]]

          [[inputs.processes]]

          [[inputs.system]]
            fielddrop = ["uptime_format"]

          [[inputs.net]]
            ignore_protocol_stats = true

          [[inputs.procstat]]
          ## pattern as argument for pgrep (ie, pgrep -f <pattern>)
            pattern = "exporter"
        telegraf.influxdata.com/class: opentsdb
        telegraf.influxdata.com/env-fieldref-NAMESPACE: metadata.namespace
        telegraf.influxdata.com/limits-cpu: '300m'
        telegraf.influxdata.com/limits-memory: '300Mi'
      labels:
        app: redis-exporter-sentinel-v7
        exporter_object: redis
        object_mode: sentinel
        object_version: v7
    spec:
      shareProcessNamespace: true
      volumes:
        - name: grafana-redis-config
          configMap:
            name: grafana-redis-config
      containers:
      - name: redis-exporter-sentinel-v7
        image: registry-svc:25000/library/grafana/agent:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        volumeMounts:  
          - name: grafana-redis-config
            mountPath: /grafana_agent_config
        args:
          - -server.http.address=0.0.0.0:12345
          - -config.file /grafana_agent_config/redis-sentinel-v7.yml
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - containerPort: 12345

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-exporter-sentinel-v7
  name: redis-exporter-sentinel-v7
  namespace: redis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "12345"
    prometheus.io/path: '/integrations/redis_exporter/metrics'
spec:
  ports:
  - port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: redis-exporter-sentinel-v7
